#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd >/dev/null || sxhkd &

sh "$HOME/.config/polybar/launch.sh" &

#autostart
sh "$HOME/.config/i3/startup.sh" &

pgrep bspswallow || bspswallow &

# Fix Mouse cursor on startup
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &

m=$(bspc query -M | wc -l)

if [ "$m" = 1 ]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &
elif [ "$m" = 2 ]; then
    bspc monitor DP3 -d 1 2 3 4 5 &
    bspc monitor DP1 -d 6 7 8 9 10 &
else
    bspc monitor DP1 -r
fi

# bspc config ignore_ewmh_focus true


bspc config border_width 1
bspc config window_gap 6
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config normal_border_color	  "#4c566a"
bspc config active_border_color	  "#1e1e1e"
bspc config focused_border_color  "#96CDFB"
bspc config presel_feedback_color "#F5C2E7"
bspc config urgent_border_color   "#F28FAD"

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config pointer_modifier super
# bspc config pointer_action1 resize_side
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

#layouts
bsp-layout set tall 1 -- --master-size 0.6
bsp-layout set monocle 4

# 1 > terminal
#bspc rule -a kittymain desktop='^1' follow=on

# 2 > web
bspc rule -a Google-chrome desktop='^2' follow=on focus=on

bspc rule -a Code desktop='^3' follow=on

bspc rule -a jetbrains-goland desktop='^4' follow=on
bspc rule -a jetbrains-phpstorm desktop='^4' follow=on

bspc rule -a Slack desktop='^7' follow=on

bspc rule -a GitHub Desktop desktop='^8' follow=on

bspc rule -a Mailspring desktop='^9' follow=on

bspc rule -a "Org.gnome.Nautilus" state=floating
bspc rule -a "Lxappearance" state=floating
bspc rule -a "Arandr" state=floating

bspc rule -a '*:floating' state=floating
bspc rule -a '*:pop-up' state=floating


# bspc rule -a Screenkey manage=off

# start terminal always
if [ $(xdotool search --class "kittymain" | wc -l) = 0 ]; then
    bspc desktop -f 1
    kitty --class=kittymain &
fi


