#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &


#Fix Mouse cursor on startup
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &

m=$(bspc query -M | wc -l)

if [ "$m" = 1 ]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &
elif [ "$m" = 2 ]; then
    bspc monitor DP1 -d 1 2 3 4 5 &
    bspc monitor HDMI1 -d 6 7 8 9 10 &
else
    bspc monitor HDMI1 -r
fi

bspc config ignore_ewmh_focus true
bspc config border_width         1
bspc config window_gap          4
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#F28FAD"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config pointer_modifier super
# bspc config pointer_action1 resize_side
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a '*:floating' state=floating
bspc rule -a '*:pop-up' state=floating

# 1 > terminal
bspc rule -a kittymain desktop='^1' follow=false focus=false

# 2 > web
bspc rule -a Google-chrome desktop='^2' follow=fasle focus=fasle
