#!/bin/env sh

read -r bat_status </sys/class/power_supply/BAT0/status
read -r bat_capacity </sys/class/power_supply/BAT0/capacity
color="^c#D9E0EE^"
if [ "$bat_status" = "Charging" ]; then
	bat_status="⚡"
	color="^c#ABE9B3^"
elif [ "$bat_capacity" -gt 80 ]; then
	bat_status=" "
	color="^c#ABE9B3^"
elif [ "$bat_capacity" -gt 60 ]; then
	bat_status=" "
	color="^c#FAE3B0^"
elif [ "$bat_capacity" -gt 40 ]; then
	bat_status=" "
	color="^c#F5C2E7^"
elif [ "$bat_capacity" -gt 20 ]; then
	bat_status=" "
	color="^c#F28FAD^"
else
	bat_status="?"
	if [ "$bat_status" != "Charging" ]; then
		notify-send --urgency=critical "Low Battery $bat_capacity"
	fi
fi

echo "$color$bat_status $bat_capacity%^d^"
