#!/bin/env sh

bat_color=\#ffffff
read -r bat_status </sys/class/power_supply/BAT0/status
read -r bat_capacity </sys/class/power_supply/BAT0/capacity
if [ "$bat_status" = "Charging" ]; then
	bat_status="⚡"
elif [ "$bat_capacity" -gt 80 ]; then
	bat_status=" "
	bat_color=\#ABE9B3
elif [ "$bat_capacity" -gt 60 ]; then
	bat_status=" "
	bat_color=\#F2CDCD
elif [ "$bat_capacity" -gt 40 ]; then
	bat_status=" "
	bat_color=\#FAE3B0
elif [ "$bat_capacity" -gt 20 ]; then
	bat_status=" "
	bat_color=\#F28FAD
else
	bat_status="?"
fi

echo "$bat_status $bat_capacity%"
echo
echo $bat_color
