#!/bin/sh

internal_monitor=eDP1
external_main_monitor=DP3
external_secondary_monitor=DP1

monitor_add() {
	desktops=5 # How many desktops to move to the second monitor

	for desktop in $(bspc query -D -m $external_main_monitor | tail -n "$desktops")
    do
            bspc desktop $desktop --to-monitor $external_secondary_monitor
    done

  # Remove "Desktop" created by bspwm
  bspc desktop Desktop --remove
}

monitor_remove() {
	bspc monitor $external_main_monitor -a Desktop # Temp desktop because one desktop required per monitor

	# Move everything to external monitor to reorder desktops
	for desktop in $(bspc query -D -m $external_main_monitor)
	do
		bspc desktop $desktop --to-monitor $external_secondary_monitor
	done

	# Now move everything back to internal monitor
	bspc monitor $external_secondary_monitor -a Desktop # Temp desktop

	for desktop in $(bspc query -D -m $external_secondary_monitor)
	do
		bspc desktop $desktop --to-monitor $external_main_monitor
	done

	bspc desktop Desktop --remove # Remove temp desktops
}

if [[ $(xrandr -q | grep "$external_secondary_monitor connected") ]]; then
    monitor_add
else
    monitor_remove
fi

set-wallpaper

$HOME/.config/polybar/launch.sh
