#!/bin/sh
PRIMARY_MONITOR=$(xrandr | sed -n 's/^\(\S\+\).*primary.*$/\1/p')
MONITOR_COUNT=$(xrandr --listactivemonitors | sed -n '2,$s/^.*\s\(\S\+\)$/\1/p' | wc -l)
desktops=5

if [ $(bspc query -D -m $PRIMARY_MONITOR | wc -l) -lt 5 ]; then
	bspc monitor $PRIMARY_MONITOR -d 1 2 3 4 5 6 7 8 9 0 &
fi

if [ $MONITOR_COUNT == 2 ]; then
	for entry in $(xrandr --listactivemonitors | sed -n '2,$s/^.*\s\(\S\+\)$/\1/p'); do
		if [ "$entry" != $(xrandr | sed -n 's/^\(\S\+\).*primary.*$/\1/p') ]; then
			for desktop in $(bspc query -D -m $PRIMARY_MONITOR | tac | sed "$desktops"q | tac)
			do
				bspc desktop $desktop --to-monitor $entry
			done
		fi
		bspc desktop Desktop --remove
	done
elif [ $MONITOR_COUNT == 1 ]; then
	for desktop in $(bspc query -D)
	do
		bspc desktop $desktop --to-monitor $PRIMARY_MONITOR
	done
fi

set-wallpaper

$HOME/.config/polybar/launch.sh &
