#!/bin/bash

function send_notification() {
	# brightness=$(printf "%.0f\n" eval($(brightnessctl g)/1000))

	brightness=$(printf "%.0f\n" $(brightnessctl -m | awk -F, '{print substr($4, 0, length($4)-1)}'))

	dunstify -a "changebrightness" -u low -r 9991 -h int:value:"$brightness" -i "brightness" "Brightness: $brightness%" -t 2000
}

case $1 in
up)
	brightnessctl -q set 10%+
	send_notification $1
	;;
down)
	brightnessctl --min-val=2 -q set 10%-
	send_notification $1
	;;
esac
