#!/bin/sh

# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "No\\nYes" | /usr/bin/rofi -dmenu  -p "$1" -i -theme-str '@import "prompt.rasi"')" = "Yes" ] && $2
