#! /bin/sh
output='/home/pankaj/Pictures/screenshots/%Y-%m-%d-%T-screenshot.png'

case "$1" in
	"select") scrot "$output" --select --line mode=edge || exit ;;
	"window") scrot "$output" --focused --border || exit ;;
	*) scrot "$output" --select || exit ;;
esac

notify-send "Screenshot taken."
